# Generated by Django 5.2.15 on 2026-06-26 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('document_created', 'Document created'), ('document_updated', 'Document updated'), ('document_status_changed', 'Document status changed'), ('file_uploaded', 'File uploaded'), ('document_viewed', 'Document viewed'), ('request_registered', 'Request registered'), ('request_approved', 'Request approved'), ('request_rejected', 'Request rejected'), ('implementation_record_registered', 'Implementation record registered'), ('controlled_copy_delivered', 'Controlled copy delivered'), ('controlled_copy_retired', 'Controlled copy retired'), ('report_generated', 'Report generated'), ('permission_changed', 'Permission changed'), ('other', 'Other')], max_length=50, verbose_name='action')),
                ('module', models.CharField(max_length=100, verbose_name='module')),
                ('entity_type', models.CharField(blank=True, max_length=100, verbose_name='entity type')),
                ('entity_id', models.CharField(blank=True, max_length=100, verbose_name='entity id')),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('denied', 'Denied'), ('warning', 'Warning')], max_length=20, verbose_name='result')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('before_data', models.JSONField(blank=True, null=True, verbose_name='before data')),
                ('after_data', models.JSONField(blank=True, null=True, verbose_name='after data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ['-created_at'],
            },
        ),
    ]
