# Generated by Django 5.2.15 on 2026-06-23 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_types', '0001_initial'),
        ('documents', '0002_documentcodesequence'),
        ('organizational_units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('create', 'Creation'), ('modify', 'Modification'), ('review', 'Review'), ('obsolete', 'Decommission / obsolescence'), ('update', 'Update'), ('other', 'Other')], max_length=20, verbose_name='request type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('received', 'Received by O&M'), ('in_review', 'In review'), ('observed', 'Observed'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='draft', max_length=20, verbose_name='status')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_requests', to='document_types.documenttype', verbose_name='document type')),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_requests', to='organizational_units.organizationalunit', verbose_name='organizational unit')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_requests', to='documents.document', verbose_name='related document')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_requests', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
            ],
            options={
                'verbose_name': 'document request',
                'verbose_name_plural': 'document requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
