# Generated by Django 5.2.15 on 2026-06-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizational_units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_technical_user',
            field=models.BooleanField(default=False, verbose_name='technical user'),
        ),
        migrations.AddField(
            model_name='user',
            name='organizational_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizational_units.organizationalunit', verbose_name='organizational unit'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('oym_admin', 'O&M functional administrator'), ('oym_analyst', 'O&M analyst'), ('executing_unit', 'Executing unit'), ('reader', 'Reader'), ('systems_tech_admin', 'Systems technical administrator'), ('auditor', 'Auditor')], default='reader', max_length=50, verbose_name='role'),
        ),
    ]
