# Generated by Django 5.2.15 on 2026-06-26 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_documentcodesequence'),
        ('organizational_units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_number', models.CharField(max_length=50, verbose_name='copy number')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='retired at')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('delivered', 'Delivered'), ('active', 'Active'), ('retired', 'Retired'), ('cancelled', 'Cancelled')], default='registered', max_length=20, verbose_name='status')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='evidence reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_controlled_copies', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_copies', to='documents.document', verbose_name='document')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_copies', to='documents.documentversion', verbose_name='document version')),
                ('receiver_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_controlled_copies', to='organizational_units.organizationalunit', verbose_name='receiver unit')),
                ('receiver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_controlled_copies', to=settings.AUTH_USER_MODEL, verbose_name='receiver user')),
            ],
            options={
                'verbose_name': 'controlled copy',
                'verbose_name_plural': 'controlled copies',
                'ordering': ['document__code', 'copy_number'],
                'constraints': [models.UniqueConstraint(fields=('document_version', 'copy_number'), name='unique_controlled_copy_number_per_version')],
            },
        ),
    ]
