# Generated by Django 5.2.15 on 2026-06-23 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_types', '0001_initial'),
        ('organizational_units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('under_review', 'Under review'), ('observed', 'Observed'), ('approved', 'Approved'), ('published', 'Published'), ('active', 'Active'), ('expired', 'Expired'), ('obsolete', 'Obsolete'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='document_types.documenttype', verbose_name='document type')),
                ('owner_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to='organizational_units.organizationalunit', verbose_name='owner unit')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=50, verbose_name='version number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('under_review', 'Under review'), ('observed', 'Observed'), ('approved', 'Approved'), ('published', 'Published'), ('active', 'Active'), ('expired', 'Expired'), ('obsolete', 'Obsolete'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='issue date')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='effective date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='expiration date')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('obsolete_at', models.DateTimeField(blank=True, null=True, verbose_name='obsolete at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_versions', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='document')),
            ],
            options={
                'verbose_name': 'document version',
                'verbose_name_plural': 'document versions',
                'ordering': ['document__code', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='content type')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='size bytes')),
                ('file_hash', models.CharField(blank=True, max_length=128, verbose_name='file hash')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_document_files', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.documentversion', verbose_name='document version')),
            ],
            options={
                'verbose_name': 'document file',
                'verbose_name_plural': 'document files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion', verbose_name='current version'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_document_version_number'),
        ),
    ]
