# Generated by Django 5.2.15 on 2026-06-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_types', '0001_initial'),
        ('documents', '0001_initial'),
        ('organizational_units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=50, verbose_name='prefix')),
                ('current_number', models.PositiveIntegerField(verbose_name='current number')),
                ('padding', models.PositiveSmallIntegerField(verbose_name='padding')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_sequences', to='document_types.documenttype', verbose_name='document type')),
                ('organizational_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_code_sequences', to='organizational_units.organizationalunit', verbose_name='organizational unit')),
            ],
            options={
                'verbose_name': 'document code sequence',
                'verbose_name_plural': 'document code sequences',
                'ordering': ['document_type__code', 'organizational_unit__code', 'prefix'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('organizational_unit__isnull', False)), fields=('document_type', 'organizational_unit', 'prefix'), name='unique_code_sequence_with_unit'), models.UniqueConstraint(condition=models.Q(('organizational_unit__isnull', True)), fields=('document_type', 'prefix'), name='unique_code_sequence_without_unit')],
            },
        ),
    ]
