# Generated by Django 5.2.15 on 2026-06-26 17:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_documentcodesequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='assigned at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('interpreted_at', models.DateTimeField(blank=True, null=True, verbose_name='interpreted at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('implemented_at', models.DateTimeField(blank=True, null=True, verbose_name='implemented at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('read', 'Read'), ('interpreted', 'Interpreted'), ('accepted', 'Accepted'), ('implemented', 'Implemented'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='implementation_records', to='documents.document', verbose_name='document')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='implementation_records', to='documents.documentversion', verbose_name='document version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='implementation_records', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'implementation record',
                'verbose_name_plural': 'implementation records',
                'ordering': ['document__code', 'document_version__version_number', 'user__email'],
                'constraints': [models.UniqueConstraint(fields=('user', 'document_version'), name='unique_implementation_record_per_user_version')],
            },
        ),
    ]
